APPLICATION_ID: '009c9d52-59a5-453b-922f-9ce1a21e087f'
ACCESS_KEY: 'pk_hXd96JoI7peFuXfPzm4kQmgMTE4V7w0De9Wf7pqG2VG'
CATEGORY_API_URL: 'https://openapi.rakuten.co.jp/recipems/api/Recipe/CategoryList/20170426'
